### ISSUE TITLE
Heroku site is not up

### ISSUE THREAD

**Issue by ghost** [jankuca/ng-scroller#1]

**Comment by jankuca** [comment]
There are currently only these two demos:
- [Twitter Feed Demo](http://ngscroller.herokuapp.com/examples/twitter.html)
- [Facebook Demo](http://ngscroller.herokuapp.com/examples/facebook.html)

An actual site and docs will be added later.

**Comment by ghost** [comment]
That's cool, it was just a bit confusing as their is a link on the top of the repo. Might be helpful to others to replace that blank link or just have a simple page with links to those 2 examples. Only way I saw them was from medium.com, might have people coming from other places as well.

**Comment by jankuca** [comment]
Check it out! http://ngscroller.herokuapp.com
