### ISSUE TITLE
The behavior of ng-scroller-repeat differs from ng-repeat

### ISSUE THREAD

**Issue by gsklee** [jankuca/ng-scroller#4]
While an element with the `ng-repeat` directive itself acts as a clone template, an element with the `ng-scroller-repeat` directive is itself a **container to the clone template** instead. This deviation in API design is bound to cause confusion.

It is better to change the API design so that `ng-scroller-repeat` mimics the usage experience of `ng-repeat` - or, if not possible/feasible, consider changing the name of the directive so that it no longer falsely hinting at a resemblance to `ng-repeat`.

**Comment by jankuca** [comment]
Thanks for the suggestion. I feel the same. The only reason it is not on the template itself is that the intermediate element is required and just having a `<div>` with no attributes (possibly) on it might seem strange.

Let me think about this a bit.

**Comment by gsklee** [comment]
How about making `ng-scroller` element-only (`restrict: 'E'`) and hide that intermediate `<div>` inside the template of the directive?

**Comment by jankuca** [comment]
Sounds reasonable.
