### ISSUE TITLE
Could you please write some installation instructions?

### ISSUE THREAD

**Issue by akarelas** [jankuca/ng-scroller#5]
I'm not very familiar with bower, and don't know what to do here in order to use ng-scroller in my website. Apparently `bower search scroller` doesn't return ng-scroller, so I can't just do: bower install ng-scroller

**Comment by akarelas** [comment]
Unless I should `<script src="...">` five .js files (which I doubt was your intention)

**Comment by akarelas** [comment]
I just saw `build.sh` in the root directory of this repository. In understand the bower command, and can execute it, but cannot execute `runner deps` because there is no `runner` package in ubuntu. Many packages contain a runner executable. Which one should I choose?

**Comment by jankuca** [comment]
Hi, simply running `npm install` in the project directory should be enough to use this.

**Comment by akarelas** [comment]
Hello! `npm install` ran very nicely. Where can I find now the .js file to include in `<script src>` tags? And is there only one .js file I need to include or are there dependencies?

**Comment by akarelas** [comment]
I'm asking because there's literally hundreds of .js files produced under `./node_modules`

**Comment by jankuca** [comment]
I am not sure if you are familiar with the Google Closure Tools and how to build apps using the Google Closure Library. I am currently building this directive on top of this library and including it in an app is not as simple as adding a `<script>` tag to the page.

The `runner` command is configured via the `client.json` file to create the `/examples/build/twitter-deps.js` and `/examples/build/facebook-deps.js` files.

If you want to play with the directive, you are best just **copying one of the examples and editing them**. Look at the `/examples/twitter/js/main.js` file to see how is the directive included—there are calls to `goog.require('ng.Scroller')` and `module.directive('ngScroller', ...)`.

I have not got to creating a general build script one could use to include the directive in a non-Google Closure-based project.

**Comment by akarelas** [comment]
Ok thanks. If creating such a script is in the plans for the future, I'll be happy.

**Comment by akarelas** [comment]
I'll be looking forward to downloading the non-closure version of the library.

**Comment by jankuca** [comment]
Check it out! http://ngscroller.herokuapp.com

**Comment by akarelas** [comment]
Excellent! Thanks! I got up from bed to try it!
