### ISSUE TITLE
Request Commit Distribution Files to Git or Fix Build Process

### ISSUE THREAD

**Issue by michaelahlers** [jankuca/ng-scroller#8]
Currently, `dist` is empty, and the build process fails (see truncated output below).

```
$ npm install
npm WARN package.json ng-scroller@ No repository field.

> ng-scroller@ postinstall ng-scroller
> ./build.sh

sh: ./build.sh: Permission denied
npm ERR! weird error 126
npm ERR! not ok code 0
```

Set proper permissions on the script, and it still fails.

```
$ chmod +x build.sh 
$ ./build.sh 
-----------------------------------------
Update available: 1.2.6 (current: 1.2.5)
Run npm update -g bower to update
-----------------------------------------

Building app dist
Running task compile
  Cannot find Closure Library DepsWriter
```

Can you commit a build? Or, better yet, add GitHub releases?

**Comment by michaelahlers** [comment]
Temporary workaround: point to `http://ngscroller.herokuapp.com/dist/ng-scroller.min.js`.

**Comment by jankuca** [comment]
What platform are you on?

**Comment by michaelahlers** [comment]
OS X. And I just realized this ticket is probably invalid: I had tried installing with Bower and unthinkingly went into its install directory to run `npm`.

**Comment by michaelahlers** [comment]
Okay, non-issue when I clone from GitHub. Sorry about that!

**Comment by jankuca** [comment]
Right, you can only build from a github repo clone.
